version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing SAM CLI"
      - pip install aws-sam-cli
  pre_build:
    commands:
      - echo "Installing Python dependencies"
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Building SAM application"
      - sam build
  post_build:
    commands:
      - echo "Deploying to AWS"
      - sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name calico-cat-api --capabilities CAPABILITY_IAM --region $AWS_DEFAULT_REGION
artifacts:
  files:
    - template.yaml
    - .aws-sam/**/*
  name: calico-cat-api